### ISSUE TITLE
[Bug Report/Feeback]

### ISSUE THREAD

**Issue by lzmch** [ly525/luban-h5#249]
**问题描述**
按照quickStart文档中的第二种方法报错：# 新开一个终端，在项目根目录执行如下命令cd front-end/h5 && yarn && yarn build:engine && yarn dev

**环境描述/版本信息 (请完成如下信息)**
 - OS: Windows
node v12.16.1
yarn 1.22.4
 - 本地开发版本 

**如何复现**

复现步骤
1.在gitee上下载压缩包，本地展开后执行命令：cd front-end/h5 && yarn && yarn build:engine && yarn dev
报以下错误：
```
-------------
Done in 53.72s.
yarn run v1.22.4
$ vue-cli-service serve
 INFO  Starting development server...
98% after emitting CopyPlugin
 ERROR  Failed to compile with 2 errors                                                                          8:50:19
 error  in ./src/components/core/editor/edit-panel/props.js
Module build failed (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
TypeError: Cannot read property 'range' of null
Occurred while linting F:\vue\luban-h5\front-end\h5\src\components\core\editor\edit-panel\props.js:43
    at SourceCode.getTokenBefore (F:\vue\luban-h5\front-end\h5\node_modules\eslint\lib\token-store\index.js:303:18)
    at checkSpacingBefore (F:\vue\luban-h5\front-end\h5\node_modules\eslint\lib\rules\template-curly-spacing.js:60:42)
-----------------
 error  in ./src/locales/index.js
Module build failed (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
TypeError: Cannot read property 'range' of null
Occurred while linting F:\vue\luban-h5\front-end\h5\src\locales\index.js:39
    at SourceCode.getTokenBefore (F:\vue\luban-h5\front-end\h5\node_modules\eslint\lib\token-store\index.js:303:18)
```

**预期结果**
能正常执行

**截图**
如果可以的话，附上截图

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by ly525** [comment]
`yarn add babel-eslint@8.0.1` 试试

**Comment by ly525** [comment]
fixed in c56da70a2391d23ea8955f05cebfbb7944912d55
