### ISSUE TITLE
项目安装过程中很多error，项目无法启动

### ISSUE THREAD

**Issue by nangongfeng1** [ly525/luban-h5#470]
**问题描述**
项目安装过程中很多error，项目无法启动

**环境描述/版本信息 (请完成如下信息)**
 - OS: Ubuntu 24.04.1-desktop
 - Node ：14.18.3
 - 一键体验版本

以下是一键脚本的信息系
root@tchan:/home/tchan/桌面/luban-h5# ./luban-h5.sh init
yarn install v1.22.22
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.84s.
yarn run v1.22.22
$ npm run build:editor && npm run build:engine
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1734346978579-0.8252713986585987/node but npm is using /root/.nvm/versions/node/v14.18.3/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> luban-h5@0.0.0 build:editor /home/tchan/桌面/luban-h5/front-end/h5
> cross-env PAGE=EDITOR vue-cli-service build

⠋  Building for production...Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
⠴  Building for production...DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($checkbox-size, 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
54 │         top: $checkbox-size / 4 - 1px ;
   │              ^^^^^^^^^^^^^^^^^^
   ╵
    stdin 54:8  root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($checkbox-size, 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
55 │         left: $checkbox-size / 4 * 3 - 1px;
   │               ^^^^^^^^^^^^^^^^^^
   ╵
    stdin 55:9  root stylesheet

⠧  Building for production...

 WARNING  Compiled with 2 warnings                                   下午7:03:16

 warning  

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  img/fontawesome-webfont.912ec66d.svg (434 KiB)
  js/chunk-777e5a06.c51651fb.js (2.36 MiB)
  js/chunk-vendors.a4d8177f.js (2.24 MiB)

 warning  

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  index (2.3 MiB)
      js/chunk-vendors.a4d8177f.js
      js/index.76e2d857.js

  File                                      Size             Gzipped

  ../../back-end/h5-api/build-editor/js/    2413.76 KiB      703.71 KiB
  chunk-777e5a06.c51651fb.js
  ../../back-end/h5-api/build-editor/js/    2298.81 KiB      594.53 KiB
  chunk-vendors.a4d8177f.js
  ../../back-end/h5-api/build-editor/js/    193.40 KiB       49.96 KiB
  chunk-4b09c6c0.31d37bbf.js
  ../../back-end/h5-api/build-editor/js/    71.76 KiB        25.30 KiB
  chunk-2d0be333.4e894ce9.js
  ../../back-end/h5-api/build-editor/js/    58.40 KiB        18.52 KiB
  chunk-78cceec4.de0f941f.js
  ../../back-end/h5-api/build-editor/js/    57.92 KiB        17.01 KiB
  index.76e2d857.js
  ../../back-end/h5-api/build-editor/js/    9.49 KiB         3.15 KiB
  chunk-304e8dc0.eabd1afe.js
  ../../back-end/h5-api/build-editor/js/    9.41 KiB         3.14 KiB
  chunk-225d8217.3f98ca21.js
  ../../back-end/h5-api/build-editor/pre    2.45 KiB         0.85 KiB
  cache-manifest.fe5c0948dd05c31ae906194
  69e8821ea.js
  ../../back-end/h5-api/build-editor/js/    2.24 KiB         1.04 KiB
  chunk-64483f7b.6efc2950.js
  ../../back-end/h5-api/build-editor/js/    2.09 KiB         1.05 KiB
  chunk-477cf947.d5afa733.js
  ../../back-end/h5-api/build-editor/js/    1.99 KiB         0.95 KiB
  chunk-2d210b9d.2e6ee9f1.js
  ../../back-end/h5-api/build-editor/js/    1.35 KiB         0.63 KiB
  chunk-2d0bb26d.08007404.js
  ../../back-end/h5-api/build-editor/ser    0.94 KiB         0.54 KiB
  vice-worker.js

  Images and other types of assets omitted.

 DONE  Build complete. The ../../back-end/h5-api/build-editor directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
                                  
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1734346978579-0.8252713986585987/node but npm is using /root/.nvm/versions/node/v14.18.3/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> luban-h5@0.0.0 build:engine /home/tchan/桌面/luban-h5/front-end/h5
> cross-env PAGE=ENGINE vue-cli-service build --target lib --name engine ./src/engine-entry.js

⠋  Building for production as library (commonjs,umd,umd-min)...Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
⠏  Building for production as library (commonjs,umd,umd-min)...DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($checkbox-size, 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
54 │         top: $checkbox-size / 4 - 1px ;
   │              ^^^^^^^^^^^^^^^^^^
   ╵
    stdin 54:8  root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($checkbox-size, 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
55 │         left: $checkbox-size / 4 * 3 - 1px;
   │               ^^^^^^^^^^^^^^^^^^
   ╵
    stdin 55:9  root stylesheet

⠋  Building for production as library (commonjs,umd,umd-min)...DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($checkbox-size, 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
54 │         top: $checkbox-size / 4 - 1px ;
   │              ^^^^^^^^^^^^^^^^^^
   ╵
    stdin 54:8  root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($checkbox-size, 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
54 │         top: $checkbox-size / 4 - 1px ;
   │              ^^^^^^^^^^^^^^^^^^
   ╵
    stdin 54:8  root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($checkbox-size, 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
55 │         left: $checkbox-size / 4 * 3 - 1px;
   │               ^^^^^^^^^^^^^^^^^^
   ╵
    stdin 55:9  root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($checkbox-size, 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
55 │         left: $checkbox-size / 4 * 3 - 1px;
   │               ^^^^^^^^^^^^^^^^^^
   ╵
    stdin 55:9  root stylesheet

⠧  Building for production as library (commonjs,umd,umd-min)...

 WARNING  Compiled with 3 warnings                                   下午7:03:35

 warning  

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  engine.umd.js (3.04 MiB)

 warning  

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  engine.umd (3.04 MiB)
      engine.umd.js

 warning  

webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

⠇  Building for production as library (commonjs,umd,umd-min)...

 WARNING  Compiled with 3 warnings                                   下午7:03:36

 warning  

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  engine.common.js (3.04 MiB)

 warning  

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  engine.common (3.04 MiB)
      engine.common.js

 warning  

webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

 WARNING  Compiled with 3 warnings                                   下午7:03:36

 warning  

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  engine.umd.min.js (1.48 MiB)

 warning  

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  engine.umd.min (1.48 MiB)
      engine.umd.min.js

 warning  

webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

  File                                      Size             Gzipped

  ../../back-end/h5-api/public/engine-as    1520.50 KiB      473.62 KiB
  sets/engine.umd.min.js
  ../../back-end/h5-api/public/engine-as    3112.29 KiB      730.10 KiB
  sets/engine.umd.js
  ../../back-end/h5-api/public/engine-as    3111.82 KiB      729.87 KiB
  sets/engine.common.js

  Images and other types of assets omitted.

Done in 38.51s.
yarn install v1.22.22
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "strapi-admin > bootstrap@4.6.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning "strapi-admin > bootstrap@4.6.1" has unmet peer dependency "popper.js@^1.16.1".
warning "strapi-plugin-users-permissions > grant-koa@5.4.8" has unmet peer dependency "koa@>=2.0.0".
warning Workspaces can only be enabled in private projects.
[5/5] Building fresh packages...
[1/14] ⠂ sqlite3
[-/14] ⠂ waiting...
[-/14] ⠄ waiting...
[14/14] ⠄ sharp
error /home/tchan/桌面/luban-h5/back-end/h5-api/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /home/tchan/桌面/luban-h5/back-end/h5-api/node_modules/sharp
Output:
info sharp Using cached /root/.npm/_libvips/libvips-8.10.5-linux-x64.tar.br
prebuild-install WARN install socket hang up
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.18.3 | linux | x64
gyp info find Python using Python version 3.12.3 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/root/.nvm/versions/node/v14.18.3/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/tchan/桌面/luban-h5/back-end/h5-api/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.nvm/versions/node/v14.18.3/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/14.18.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/14.18.3',
gyp info spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v14.18.3/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/14.18.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/tchan/桌面/luban-h5/back-end/h5-api/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "/root/.nvm/versions/node/v14.18.3/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
             ^^^^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.18.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.18.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
           ^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.18.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 520, in gyp_main
    [generator, flat_list, targets, data] = Load(
                                            ^^^^^
  File "/root/.nvm/versions/node/v14.18.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 136, in Load
    result = gyp.input.Load(build_files, default_variables, includes[:],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.18.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2782, in Load
    LoadTargetBuildFile(build_file, data, aux_data,
  File "/root/.nvm/versions/node/v14.18.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
    build_file_data = LoadOneBuildFile(build_file_path, data, aux_data,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.nvm/versions/node/v14.18.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 234, in LoadOneBuildFile
    build_file_contents = open(build_file_path, 'rU').read()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU' while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/root/.nvm/versions/node/v14.18.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Linux 6.8.0-50-generic
gyp ERR! command "/root/.nvm/versions/node/v14.18.3/bin/node" "/root/.nvm/versions/node/v14.18.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/tchan/桌面/luban-h5/back-end/h5-api/node_modules/sharp
gyp ERR! node -v v14.18.3

**Comment by ly525** [comment]
fixed in https://github.com/ly525/luban-h5/commit/df183155cd0396daf74c548a2024cd5012d985af
